"""HLS C++ code generation.

`emit_graph` produces a synthesizable Vitis HLS top function (DATAFLOW) that calls
one function per layer. `emit_testbench` adds a `main()` that reads integers from
stdin and writes the network output to stdout, which is how the bit-exactness test
compares against the golden PyTorch executor.

The output is plain-C++ compilable: `#pragma HLS ...` is ignored by clang/g++, and
the datapath uses fixed-width integer types rather than `ap_int`.
"""
from __future__ import annotations

from ..ir import Add
from .layers import emit_layer

HEADER = """// Generated by hls-estimate. Do not edit.
// Synthesizable Vitis HLS C++; also compiles as plain C++ (pragmas ignored).
#include <cstdint>
#include <cstdio>

typedef int32_t data_t;   // quantized activations/weights (int8/int4 valued)
typedef int64_t acc_t;    // MAC accumulator
"""


def _buffer_name(tensor: str) -> str:
    return f"buf_{tensor}"


def emit_graph(graph, name: str = "net") -> str:
    """Emit layer functions plus the DATAFLOW top-level function."""
    parts = [HEADER]
    for node in graph.nodes:
        parts.append(emit_layer(node))

    specs = graph.tensors()
    in_name = graph.input_spec.name
    out_name = graph.output_spec.name

    body = [f"""
void {name}(const data_t {in_name}[{graph.input_spec.numel()}],
    data_t {out_name}[{graph.output_spec.numel()}]) {{
#pragma HLS DATAFLOW"""]

    # Intermediate tensors become local buffers; graph input/output are the ports.
    for node in graph.nodes:
        if node.output == out_name:
            continue
        n_elems = specs[node.output].numel()
        body.append(f"  static data_t {_buffer_name(node.output)}[{n_elems}];")

    def ref(tensor: str) -> str:
        if tensor == in_name:
            return in_name
        if tensor == out_name:
            return out_name
        return _buffer_name(tensor)

    for node in graph.nodes:
        args = ", ".join(ref(t) for t in node.inputs) + ", " + ref(node.output)
        body.append(f"  layer_{node.name}({args});")
    body.append("}")
    parts.append("\n".join(body))
    return "\n".join(parts) + "\n"


def emit_testbench(graph, name: str = "net") -> str:
    n_in = graph.input_spec.numel()
    n_out = graph.output_spec.numel()
    return f"""
// Test bench: reads {n_in} integers from stdin, prints {n_out} integers to stdout.
int main() {{
  static data_t x[{n_in}];
  static data_t y[{n_out}];
  for (int i = 0; i < {n_in}; ++i) {{
    long long tmp = 0;
    if (scanf("%lld", &tmp) != 1) return 1;
    x[i] = (data_t)tmp;
  }}
  {name}(x, y);
  for (int i = 0; i < {n_out}; ++i) printf("%lld\\n", (long long)y[i]);
  return 0;
}}
"""


def emit_full(graph, name: str = "net") -> str:
    """Top function + test bench in one translation unit (used by the tests)."""
    return emit_graph(graph, name) + emit_testbench(graph, name)
