/**
 * TypeScript port of hls_estimate/codegen (weights elided).
 *
 * Python is the source of truth; lib/codegen.test.ts asserts byte-identical output
 * against golden files generated from the real emitter. Whitespace matters here.
 */
import {
  convOutH,
  convOutW,
  outputNumel,
  poolOutH,
  poolOutW,
  type AddNode,
  type Conv2dNode,
  type Graph,
  type LinearNode,
  type MaxPoolNode,
  type Node,
  type ReLUNode,
} from "./model";

const HEADER = `// Generated by hls-estimate. Do not edit.
// Synthesizable Vitis HLS C++; also compiles as plain C++ (pragmas ignored).
#include <cstdint>
#include <cstdio>

typedef int32_t data_t;   // quantized activations/weights (int8/int4 valued)
typedef int64_t acc_t;    // MAC accumulator
`;

function qrange(bits: number, relu: boolean): [number, number] {
  return [relu ? 0 : -(1 << (bits - 1)), (1 << (bits - 1)) - 1];
}

function weightCount(n: Node): number {
  if (n.kind === "conv2d") return n.outCh * n.inCh * n.kh * n.kw;
  if (n.kind === "linear") return n.outFeatures * n.inFeatures;
  return 0;
}

function formatArray(name: string, count: number): string {
  return `static const data_t ${name}[${count}] = {\n  /* ${count} quantized weights elided */\n};`;
}

function pipeline(n: Node, indent: string): string {
  return n.knobs.pipeline
    ? `${indent}#pragma HLS PIPELINE II=1`
    : `${indent}#pragma HLS PIPELINE off`;
}

function requant(n: Conv2dNode | LinearNode, indent: string): string {
  const [qmin, qmax] = qrange(n.outBits, n.relu);
  const rnd = n.shift > 0 ? 1 << (n.shift - 1) : 0;
  return [
    `${indent}acc_t v = (acc * ${n.mult} + ${rnd}) >> ${n.shift};`,
    `${indent}if (v < ${qmin}) v = ${qmin};`,
    `${indent}if (v > ${qmax}) v = ${qmax};`,
  ].join("\n");
}

function emitConv(n: Conv2dNode): string {
  const oh = convOutH(n);
  const ow = convOutW(n);
  const inElems = n.inCh * n.inH * n.inW;
  const outElems = n.outCh * oh * ow;
  const w = `${n.name}_w`;
  const u = Math.max(1, n.knobs.unroll);
  const parts = [formatArray(w, weightCount(n))];
  if (n.bias) parts.push(formatArray(`${n.name}_b`, n.outCh));
  parts.push(`
static void layer_${n.name}(const data_t in[${inElems}], data_t out[${outElems}]) {
#pragma HLS ARRAY_PARTITION variable=${w} cyclic factor=${u} dim=1
  for (int oc = 0; oc < ${n.outCh}; ++oc) {
    for (int oh = 0; oh < ${oh}; ++oh) {
      for (int ow = 0; ow < ${ow}; ++ow) {
${pipeline(n, "        ")}
        acc_t acc = 0;
        for (int ic = 0; ic < ${n.inCh}; ++ic) {
          for (int kh = 0; kh < ${n.kh}; ++kh) {
            for (int kw = 0; kw < ${n.kw}; ++kw) {
              #pragma HLS UNROLL factor=${u}
              int ih = oh * ${n.stride} - ${n.pad} + kh;
              int iw = ow * ${n.stride} - ${n.pad} + kw;
              if (ih < 0 || ih >= ${n.inH} || iw < 0 || iw >= ${n.inW}) continue;
              acc_t w = (acc_t)${w}[((oc * ${n.inCh} + ic) * ${n.kh} + kh) * ${n.kw} + kw];
              acc_t a = (acc_t)in[(ic * ${n.inH} + ih) * ${n.inW} + iw];
              acc += w * a;
            }
          }
        }`);
  if (n.bias) parts.push(`        acc += (acc_t)${n.name}_b[oc];`);
  parts.push(requant(n, "        "));
  parts.push(`        out[(oc * ${oh} + oh) * ${ow} + ow] = (data_t)v;
      }
    }
  }
}`);
  return parts.join("\n");
}

function emitLinear(n: LinearNode): string {
  const w = `${n.name}_w`;
  const u = Math.max(1, n.knobs.unroll);
  const parts = [formatArray(w, weightCount(n))];
  if (n.bias) parts.push(formatArray(`${n.name}_b`, n.outFeatures));
  parts.push(`
static void layer_${n.name}(const data_t in[${n.inFeatures}], data_t out[${n.outFeatures}]) {
#pragma HLS ARRAY_PARTITION variable=${w} cyclic factor=${u} dim=1
  for (int oc = 0; oc < ${n.outFeatures}; ++oc) {
${pipeline(n, "    ")}
    acc_t acc = 0;
    for (int i = 0; i < ${n.inFeatures}; ++i) {
      #pragma HLS UNROLL factor=${u}
      acc += (acc_t)${w}[oc * ${n.inFeatures} + i] * (acc_t)in[i];
    }`);
  if (n.bias) parts.push(`    acc += (acc_t)${n.name}_b[oc];`);
  parts.push(requant(n, "    "));
  parts.push(`    out[oc] = (data_t)v;
  }
}`);
  return parts.join("\n");
}

function emitReLU(n: ReLUNode): string {
  const [qmin, qmax] = qrange(n.bits, true);
  const u = Math.max(1, n.knobs.unroll);
  return `
static void layer_${n.name}(const data_t in[${n.numel}], data_t out[${n.numel}]) {
  for (int i = 0; i < ${n.numel}; ++i) {
${pipeline(n, "    ")}
    #pragma HLS UNROLL factor=${u}
    acc_t v = (acc_t)in[i];
    if (v < ${qmin}) v = ${qmin};
    if (v > ${qmax}) v = ${qmax};
    out[i] = (data_t)v;
  }
}`;
}

function emitMaxPool(n: MaxPoolNode): string {
  const oh = poolOutH(n);
  const ow = poolOutW(n);
  const inElems = n.inCh * n.inH * n.inW;
  const outElems = n.inCh * oh * ow;
  const u = Math.max(1, n.knobs.unroll);
  return `
static void layer_${n.name}(const data_t in[${inElems}], data_t out[${outElems}]) {
  for (int c = 0; c < ${n.inCh}; ++c) {
    for (int oh = 0; oh < ${oh}; ++oh) {
      for (int ow = 0; ow < ${ow}; ++ow) {
${pipeline(n, "        ")}
        data_t best = in[(c * ${n.inH} + oh * ${n.stride}) * ${n.inW} + ow * ${n.stride}];
        for (int kh = 0; kh < ${n.kh}; ++kh) {
          for (int kw = 0; kw < ${n.kw}; ++kw) {
            #pragma HLS UNROLL factor=${u}
            data_t cand = in[(c * ${n.inH} + oh * ${n.stride} + kh) * ${n.inW}
                             + ow * ${n.stride} + kw];
            if (cand > best) best = cand;
          }
        }
        out[(c * ${oh} + oh) * ${ow} + ow] = best;
      }
    }
  }
}`;
}

function emitAdd(n: AddNode): string {
  const [qmin, qmax] = qrange(n.bits, false);
  const u = Math.max(1, n.knobs.unroll);
  return `
static void layer_${n.name}(const data_t a[${n.numel}], const data_t b[${n.numel}],
                           data_t out[${n.numel}]) {
  for (int i = 0; i < ${n.numel}; ++i) {
${pipeline(n, "    ")}
    #pragma HLS UNROLL factor=${u}
    acc_t v = (acc_t)a[i] + (acc_t)b[i];
    if (v < ${qmin}) v = ${qmin};
    if (v > ${qmax}) v = ${qmax};
    out[i] = (data_t)v;
  }
}`;
}

function emitLayer(n: Node): string {
  switch (n.kind) {
    case "conv2d":
      return emitConv(n);
    case "linear":
      return emitLinear(n);
    case "relu":
      return emitReLU(n);
    case "maxpool2d":
      return emitMaxPool(n);
    case "add":
      return emitAdd(n);
  }
}

function inputNumel(graph: Graph): number {
  return graph.inputShape.reduce((a, b) => a * b, 1);
}

export function emitGraph(graph: Graph, name = "net"): string {
  const parts = [HEADER];
  for (const node of graph.nodes) parts.push(emitLayer(node));

  const inName = "x";
  const outName = graph.nodes[graph.nodes.length - 1].output;
  const outNumel = outputNumel(graph.nodes[graph.nodes.length - 1]);

  const body = [
    `
void ${name}(const data_t ${inName}[${inputNumel(graph)}],
    data_t ${outName}[${outNumel}]) {
#pragma HLS DATAFLOW`,
  ];
  for (const node of graph.nodes) {
    if (node.output === outName) continue;
    body.push(`  static data_t buf_${node.output}[${outputNumel(node)}];`);
  }
  const ref = (tensor: string) =>
    tensor === inName || tensor === outName ? tensor : `buf_${tensor}`;
  for (const node of graph.nodes) {
    const args = [...node.inputs.map(ref), ref(node.output)].join(", ");
    body.push(`  layer_${node.name}(${args});`);
  }
  body.push("}");
  parts.push(body.join("\n"));
  return parts.join("\n") + "\n";
}

export function emitTestbench(graph: Graph, name = "net"): string {
  const nIn = inputNumel(graph);
  const nOut = outputNumel(graph.nodes[graph.nodes.length - 1]);
  return `
// Test bench: reads ${nIn} integers from stdin, prints ${nOut} integers to stdout.
int main() {
  static data_t x[${nIn}];
  static data_t y[${nOut}];
  for (int i = 0; i < ${nIn}; ++i) {
    long long tmp = 0;
    if (scanf("%lld", &tmp) != 1) return 1;
    x[i] = (data_t)tmp;
  }
  ${name}(x, y);
  for (int i = 0; i < ${nOut}; ++i) printf("%lld\\n", (long long)y[i]);
  return 0;
}
`;
}
